name: Deploy root to Blob Storage

on:
    push:
        branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: build JS
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - run: npm ci
    - run: npm run build
    - name: Set outputs
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
    - name: Check outputs
      run: echo ${{ steps.vars.outputs.sha_short }}
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: List files
      run: ls
    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob upload-batch --account-name talkstorage7443 --auth-mode key -d javascript --source dist --destination-path "${{ steps.vars.outputs.sha_short }}-root"

    - name: update import map
      run: |
          curl --location --request PATCH 'http://imd.602492b207e34b7bbd7e.germanywestcentral.aksapp.io/services?env=prod' \
          --header 'Accept: application/json' \
          --header 'Content-Type: application/json' \
          --data-raw '{
           "service": "@talk/root-config",
           "url": "https://javascript-frontdoor-gucte0ayg8f9f9ej.z01.azurefd.net/javascript/${{ steps.vars.outputs.sha_short }}-root/talk-root-config.js"
           }'
    - name: 'Build and push image'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/rootfrontend:${{ github.sha }}
        docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/rootfrontend:${{ github.sha }}

    - name: 'Deploy to Azure Container Instances'
      uses: 'azure/aci-deploy@v1'
      with:
        resource-group: ${{ secrets.RESOURCE_GROUP }}
        dns-name-label: namelabeltest
        image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/rootfrontend:${{ github.sha }}
        registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
        registry-username: ${{ secrets.REGISTRY_USERNAME }}
        registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        name: root-frontend
        location: 'germanywestcentral'
    - name: Set AKS context
      id: set-context
      uses: azure/aks-set-context@v3
      with:
        resource-group: ${{ secrets.resource_group }}
        cluster-name: talk
    - name: Setup kubectl
      id: install-kubectl
      uses: azure/setup-kubectl@v3
    - uses: Azure/k8s-create-secret@v1.1
      with:
        container-registry-url: talkcontainers.azurecr.io
        container-registry-username: ${{ secrets.REGISTRY_USERNAME }}
        container-registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        secret-name: demo-k8s-secret
    - name: Run kubectl
      run: |
        kubectl get deploy
        kubectl set image deployment/root-frontend-deployment container-root=talkcontainers.azurecr.io/containerfrontend:${{ github.sha }}
