name: Deploy root to Blob Storage

on:
    push:
        branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: build JS
      uses: actions/setup-node@v2
      with:
        node-version: '16'
    - run: npm ci
    - run: npm run build
    - uses: azure/login@v1
      with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: List files
      run: ls
    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob upload-batch --account-name talkstorage7443 --auth-mode key -d 'javascript' -s .
    - name: Purge CDN endpoint
      uses: azure/CLI@v1
      with:
        inlineScript: |
           az cdn endpoint purge --content-paths  "/*" --profile-name "javascript-frontdoor" --name "javascript-frontdoor-gucte0ayg8f9f9ej.z01.azurefd.net" --resource-group "talk_group"
    - name: logout
      run: |
            az logout
      if: always()
